# Generated by Django 3.1.5 on 2021-03-26 02:49

from django.db import migrations, models

"""
Student name: Van Phuc Tan Le
Student number: 040985238

This class creates migration based on each model object
and prepare queries to map data to the database
Command: python manage.py makemigrations covid19

"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidRecord',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=3)),
                ('nameEN', models.CharField(max_length=100)),
                ('nameFR', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('num_confirmed', models.CharField(max_length=10)),
                ('num_probable', models.CharField(max_length=10)),
                ('num_death', models.CharField(max_length=10)),
                ('num_total', models.CharField(max_length=10)),
                ('num_tested', models.CharField(max_length=10)),
                ('rate_tested', models.CharField(max_length=10)),
                ('num_today', models.CharField(max_length=10)),
                ('rate_total', models.CharField(max_length=10)),
            ],
        ),
    ]
